# 60-data-collector-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: data-collector
type: Opaque
stringData:
    # API Configuration
    API_KEY: ""
    API_BASE_URL: ""
    DECISION_IDS_ENDPOINT: str = ""
    DECISION_DOCUMENT_ENDPOINT: str = ""

    # Azure OpenAI configuration
    AZURE_OPENAI_ENDPOINT: ""
    AZURE_OPENAI_API_KEY: ""


    # Elasticsearch configuration
    ELASTICSEARCH_CERT: ""  # Path to SSL certificate if needed
    ELASTICSEARCH_USER: ""
    ELASTICSEARCH_PASSWORD: ""
